/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EcgWaveform: typeof import('./components/EcgWaveform.vue')['default']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    GlassButton: typeof import('./components/ui/GlassButton.vue')['default']
    GlassCard: typeof import('./components/ui/GlassCard.vue')['default']
    GlassPopup: typeof import('./components/ui/GlassPopup.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    ImmersiveBackground: typeof import('./components/ImmersiveBackground.vue')['default']
    LyricScroller: typeof import('./components/LyricScroller.vue')['default']
    MiniLyric: typeof import('./components/MiniLyric.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchConfigPopup: typeof import('./components/SearchConfigPopup.vue')['default']
    SearchResultPanel: typeof import('./components/SearchResultPanel.vue')['default']
    SectionHeader: typeof import('./components/ui/SectionHeader.vue')['default']
    SkeletonRow: typeof import('./components/ui/SkeletonRow.vue')['default']
    SourceBadge: typeof import('./components/SourceBadge.vue')['default']
    TrackActionSheet: typeof import('./components/TrackActionSheet.vue')['default']
    TrackItem: typeof import('./components/TrackItem.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
